
[General]
	#How many layers deep can you place backpacks inside backpacks? -1 for infinite, 0 is the same as setting 'allowBagInBag' to false.
	#Requires a world reload
	#Allowed Range: -1 ~ 5  Default: -1
	maxBagInBagLayer = -1
	#Can backpacks be put inside other backpacks?
	#Requires a world reload
	#Allowed Values: true, false  Default: true
	allowBagInBag = true
	#Should backpacks be destroyed by lava and fire?
	#Requires a world reload
	#Allowed Values: true, false  Default: true
	canBackpacksBurn = true
	#Should the backpack remain in the player's inventory if they die?
	#Requires a world reload
	#Allowed Values: true, false  Default: false
	keepBackpacksOnDeath = false

[Backpacks]

	[Backpacks.Basic]
		#Enable the basic backpack?
		#Requires a game restart
		#Allowed Values: true, false  Default: true
		basicEnable = true
		#How many rows does the basic backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 9  Default: 3
		basicRows = 3
		#How many columns does the basic backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 13  Default: 9
		basicColumns = 9

	[Backpacks.Silver]
		#How many rows does the silver backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 9  Default: 5
		silverRows = 5
		#Enable the silver backpack?
		#Requires a game restart
		#Allowed Values: true, false  Default: true
		silverEnable = true
		#How many columns does the silver backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 13  Default: 9
		silverColumns = 9

	[Backpacks.Gold]
		#Enable the gold backpack?
		#Requires a game restart
		#Allowed Values: true, false  Default: true
		goldEnable = true
		#How many rows does the gold backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 9  Default: 5
		goldRows = 5
		#How many columns does the gold backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 13  Default: 9
		goldColumns = 9

	[Backpacks.Obsidian]
		#How many rows does the obsidian backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 9  Default: 8
		obsidianRows = 8
		#Enable the obsidian backpack?
		#Requires a game restart
		#Allowed Values: true, false  Default: true
		obsidianEnable = true
		#How many columns does the obsidian backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 13  Default: 9
		obsidianColumns = 9

	[Backpacks.Iron]
		#How many rows does the iron backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 9  Default: 4
		ironRows = 4
		#How many columns does the iron backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 13  Default: 9
		ironColumns = 9
		#Enable the iron backpack?
		#Requires a game restart
		#Allowed Values: true, false  Default: true
		ironEnable = true

	[Backpacks.Diamond]
		#How many columns does the diamond backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 13  Default: 9
		diamondColumns = 9
		#Enable the diamond backpack?
		#Requires a game restart
		#Allowed Values: true, false  Default: true
		diamondEnable = true
		#How many rows does the diamond backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 9  Default: 7
		diamondRows = 7

	[Backpacks.Copper]
		#How many rows does the copper backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 9  Default: 4
		copperRows = 4
		#Enable the copper backpack?
		#Requires a game restart
		#Allowed Values: true, false  Default: true
		copperEnable = true
		#How many columns does the copper backpack have?
		#Requires a world reload
		#Allowed Range: 1 ~ 13  Default: 9
		copperColumns = 9

